# Generated by Django 3.2.4 on 2021-07-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imag',
            new_name='image',
        ),
    ]
